### ISSUE TITLE
掉pro

### ISSUE THREAD

**Issue by Noahsarker** [AaronYES/aaPanel#2]
隔会儿pro就掉了

**Comment by AaronYES** [comment]
最后执行开心那个操作 不要进行重启面板 重启后就会掉

**Comment by Noahsarker** [comment]
我有2个鸡儿，都没有重启过面板呀，都掉。

**Comment by AaronYES** [comment]
我回头看看 我这里是不重启面板就没事 我的汉化那条 有重启面板命令的

国内版有个文件注释掉就不会掉pro了 国际版还没找到

掉了的话 你在重新执行下4吧

**Comment by AaronYES** [comment]
我把宝塔国内版的文件整过来了 试试看现在还掉不 

其实不重启面板的话 理论上不会掉的
