### ISSUE TITLE
aapanel 6.8.23 official source is already unavailable

### ISSUE THREAD

**Issue by hyyz17200** [AaronYES/aaPanel#3]
Hi, 

Thanks for this nice tool.

I was trying to downgrade aapanel version but the official source is down.

If you don't mind, would you add the github fuction to the script menu?

**Comment by AaronYES** [comment]
Luckily I uploaded the old version before
[aaPanel 6.8.23](https://github.com/AaronYES/aaPanel/releases/tag/1.0)

Of course it is now possible to use it to downgrade aapanel
Please download the latest script

**Comment by hyyz17200** [comment]
Thanks!
