### ISSUE TITLE
破解无效了，能显示破解图标看起来像破解，实际插件安装后会出现错误无法使用

### ISSUE THREAD

**Issue by tippytea** [AaronYES/aaPanel#5]
我使用的是aapanel

破解后安装插件是可以装，但是使用的时候出现错误弹窗提示：
[Task Manager] plug-in has not been purchased, or it has expired!

求大佬给个解决方法

**Comment by AaronYES** [comment]
是降级后的版本吗？安装的那个插件？

**Comment by AaronYES** [comment]
我这边测试 常用的防火墙和网站统计没有问题

**Comment by tippytea** [comment]
是降级后的版本，安装的是任务管理器，装好后点设置就会出错误弹窗。

**Comment by AaronYES** [comment]
部分插件无法使用是正常的 
在中文版的宝塔面板上 本地破解也是仅仅能够使用官方提供的插件

**Comment by tippytea** [comment]
> 部分插件无法使用是正常的 在中文版的宝塔面板上 本地破解也是仅仅能够使用官方提供的插件

是大部分收费插件都有一些问题。好像破解已经对插件失效了。

**Comment by AaronYES** [comment]
这个一直是这样的吧，只能用官方提供的插件，第三方的用不了的

**Comment by tippytea** [comment]
> 这个一直是这样的吧，只能用官方提供的插件，第三方的用不了的

我说的“任务管理器”，就是官方的插件，然后我用大佬的工具破解了之后，在后来应用列表安装这个官方的“任务管理器”，可以正常安装，但是打开时提示错误[Task Manager] plug-in has not been purchased, or it has expired!。

**Comment by KenKout** [comment]
I got the same error

**Comment by KenKout** [comment]
![image](https://user-images.githubusercontent.com/54569460/188914782-5c3eeb82-fd52-4ae5-87d6-25e99dc6f0e6.png)
Got the same error
![image](https://user-images.githubusercontent.com/54569460/188914843-6df12906-ce9f-4aa3-8092-b139c42c3192.png)
